services:
      Matters\Utilities\Services\HelperFunctionService:
        class: Matters\Utilities\Services\HelperFunctionService

      Matters\Utilities\Services\FileService:
        class: Matters\Utilities\Services\FileService
        arguments:
          - @Matters\Utilities\Services\HelperFunctionService

      Matters\Utilities\Services\FlattenArrayService:
        class: Matters\Utilities\Services\FlattenArrayService

      Matters\Utilities\Services\ClassWriterService:
        class: Matters\Utilities\Services\ClassWriterService

      Matters\Utilities\Generators\DtoGeneratorService:
        class: Matters\Utilities\Generators\DtoGeneratorService
        arguments:
          - @Matters\Utilities\Services\FileService
          - @Matters\Utilities\Services\FlattenArrayService
          - @Matters\Utilities\Services\ClassWriterService