services:
      Matters\Utilities\Services\HelperFunctionService:
        class: Matters\Utilities\Services\HelperFunctionService

      Matters\Utilities\Services\FileService:
        class: Matters\Utilities\Services\FileService
        arguments:
          - @Matters\Utilities\Services\HelperFunctionService

      Matters\Utilities\Generators\DtoGeneratorService:
        class: Matters\Utilities\Generators\DtoGeneratorService
        arguments:
          - @Matters\Utilities\Services\FileService