services:
      Matters\Utilities\Services\HelperFunctionService:
        class: Matters\Utilities\Services\HelperFunctionService

      Matters\Utilities\Services\FileService:
        class: Matters\Utilities\Services\FileService
        arguments:
          - @Matters\Utilities\Services\HelperFunctionService

      Matters\Utilities\Services\FlattenArrayService:
        class: Matters\Utilities\Services\FlattenArrayService

      Matters\Utilities\Services\ProcessEnumTemplate:
        class: Matters\Utilities\Services\ProcessEnumTemplate

      Matters\Utilities\Services\VerifyEnumTemplate:
        class: Matters\Utilities\Services\VerifyEnumTemplate

      Matters\Utilities\Services\DtoClassWriterService:
        class: Matters\Utilities\Services\DtoClassWriterService

      Matters\Utilities\Services\EnumClassWriterService:
        class: Matters\Utilities\Services\EnumClassWriterService

      Matters\Utilities\Generators\DtoGeneratorService:
        class: Matters\Utilities\Generators\DtoGeneratorService
        arguments:
          - @Matters\Utilities\Services\FileService
          - @Matters\Utilities\Services\FlattenArrayService
          - @Matters\Utilities\Services\DtoClassWriterService

      Matters\Utilities\Generators\EnumGeneratorService:
        class: Matters\Utilities\Generators\EnumGeneratorService
        arguments:
          - @Matters\Utilities\Services\FileService
          - @Matters\Utilities\Services\VerifyEnumTemplate
          - @Matters\Utilities\Services\ProcessEnumTemplate
          - @Matters\Utilities\Services\EnumClassWriterService